In [92]:
from scipy.spatial import distance
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, pairwise_distances # for calculating the distances
from sklearn.metrics import jaccard_score # for calculating the jaccard_score

df = pd.read_csv(r"D:\Supervised Machine Learning lab (SMLL)\2\Practice dataset 1 Product performance.csv")
df.head() 

df1=df[['Ambience','Customer_service','Offers']]
df1.head()

point_1 = df['Ambience']
point_1 = point_1[:5]
point_2 = df['Customer_service']
point_2 = point_2[:5]

In [94]:
# computing the euclidean distance
euclidean_distance = distance.euclidean(point_1, point_2)
print(f"Euclidean Distance between {point_1} and {point_2} is :", euclidean_distance)

Euclidean Distance between 0    0.50
1   -0.14
2    0.65
3    1.52
4   -0.23
Name: Ambience, dtype: float64 and 0    1.40
1    0.92
2    0.06
3   -0.65
4    0.70
Name: Customer_service, dtype: float64 is : 2.802766490451889


In [96]:
# computing the Minkowski distance
minkowski_distance = distance.minkowski(point_1,point_2,p=3)
print(f"Minkowski Distance between {point_1} and {point_2} is :", minkowski_distance)

Minkowski Distance between 0    0.50
1   -0.14
2    0.65
3    1.52
4   -0.23
Name: Ambience, dtype: float64 and 0    1.40
1    0.92
2    0.06
3   -0.65
4    0.70
Name: Customer_service, dtype: float64 is : 2.360227941691184


In [98]:
# computing the Manhattan distance
manhattan_distance = distance.cityblock(point_1,point_2)
print("manhattan_distance b/w", point_1,'and',point_2,'is: ',manhattan_distance)

manhattan_distance b/w 0    0.50
1   -0.14
2    0.65
3    1.52
4   -0.23
Name: Ambience, dtype: float64 and 0    1.40
1    0.92
2    0.06
3   -0.65
4    0.70
Name: Customer_service, dtype: float64 is:  5.6499999999999995


In [100]:
# computing the Hamming distance
string_1 = 'euclidean'
string_2 = 'Minkowski'
hamming_distance = distance.hamming(list(string_1), list(string_2))*len(string_1)
print(f"Hamming Distance between {string_1} and {string_2} is :", hamming_distance)

Hamming Distance between euclidean and Minkowski is : 9.0


In [102]:
# Euclidean distance
euclidean_dist = pairwise_distances(df1, metric='euclidean')
print("Euclidean Distance Matrix (scikit-learn):\n", euclidean_dist)


Euclidean Distance Matrix (scikit-learn):
 [[0.00000000e+00 9.65194281e-01 1.35284885e+00 ... 2.35193537e+00
  2.14443466e+00 2.20338376e+00]
 [9.65194281e-01 0.00000000e+00 1.33648793e+00 ... 2.24908870e+00
  1.25387400e+00 1.80557470e+00]
 [1.35284885e+00 1.33648793e+00 2.10734243e-08 ... 1.04220919e+00
  1.67068848e+00 1.02142058e+00]
 ...
 [2.35193537e+00 2.24908870e+00 1.04220919e+00 ... 0.00000000e+00
  2.10888596e+00 1.09128365e+00]
 [2.14443466e+00 1.25387400e+00 1.67068848e+00 ... 2.10888596e+00
  0.00000000e+00 1.36970800e+00]
 [2.20338376e+00 1.80557470e+00 1.02142058e+00 ... 1.09128365e+00
  1.36970800e+00 0.00000000e+00]]


In [104]:
# Manhattan distance
manhattan_dist_sklearn = pairwise_distances(df1, metric='manhattan')
print("\nManhattan Distance Matrix (scikit-learn):\n", manhattan_dist_sklearn)
p = int(input("Enter the parameter that defines the distance metric: ")) # taking input of the parameter which defines the distance metric
minkowski_dist_sklearn = pairwise_distances(df1, metric='minkowski', p=p)
print("\nMinkowski Distance Matrix (p=3, scikit-learn):\n", minkowski_dist_sklearn)



Manhattan Distance Matrix (scikit-learn):
 [[0.   1.66 1.6  ... 2.98 3.64 2.73]
 [1.66 0.   2.3  ... 3.68 1.98 2.39]
 [1.6  2.3  0.   ... 1.4  2.56 1.51]
 ...
 [2.98 3.68 1.4  ... 0.   3.5  1.29]
 [3.64 1.98 2.56 ... 3.5  0.   2.21]
 [2.73 2.39 1.51 ... 1.29 2.21 0.  ]]


Enter the parameter that defines the distance metric:  2



Minkowski Distance Matrix (p=3, scikit-learn):
 [[0.         0.96519428 1.35284885 ... 2.35193537 2.14443466 2.20338376]
 [0.96519428 0.         1.33648793 ... 2.2490887  1.253874   1.8055747 ]
 [1.35284885 1.33648793 0.         ... 1.04220919 1.67068848 1.02142058]
 ...
 [2.35193537 2.2490887  1.04220919 ... 0.         2.10888596 1.09128365]
 [2.14443466 1.253874   1.67068848 ... 2.10888596 0.         1.369708  ]
 [2.20338376 1.8055747  1.02142058 ... 1.09128365 1.369708   0.        ]]


In [106]:
# Randomly generating a boolean value dataset
num_samples = 10
num_features = 5

In [108]:
# np.random.randint generates random integers from a specified low (inclusive) to high (exclusive) range.
sample_data = np.random.randint(2, size=(num_samples, num_features))
df2 = pd.DataFrame(sample_data, columns=[f'Feature_{i+1}' for i in range(num_features)])
df2

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5
0          1          0          0          0          0
1          1          0          1          0          0
2          0          0          0          1          0
3          1          1          1          1          0
4          0          1          1          1          0
5          1          0          0          1          0
6          1          0          1          1          0
7          1          0          1          0          1
8          0          1          0          0          1
9          1          0          0          0          0

In [110]:
# Calulating jaccard distances
jaccard_distances = []
index_pairs = []
for i in range(len(df2)):
    for j in range(i + 1, len(df2)):
        jaccard_distance = round(1 - jaccard_score(df2.iloc[i], df2.iloc[j]), 2)
        index_pairs.append((i+1, j+1))
        jaccard_distances.append(jaccard_distance)
jaccard_df = pd.DataFrame({'Indexes(Sample)': index_pairs, 'Jaccard Distance': jaccard_distances})
jaccard_df.head()


Indexes(Sample)  Jaccard Distance
0          (1, 2)              0.50
1          (1, 3)              1.00
2          (1, 4)              0.75
3          (1, 5)              1.00
4          (1, 6)              0.50